server:
  port: 8090

spring:
  data:
    mongodb:
      uri: mongodb://julia_nguyen:juliaNguyen98!@localhost:27017/customer?authSource=admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: false
    hostname: localhost
